### ISSUE TITLE
fix: 모임 구독 시 500 에러 발생

### ISSUE THREAD

**Issue by eun-byeol** [woowacourse-teams/2024-ody#241]
# 📝 상세 내용
- [x] 모임 구독 시 `모임 구독에 실패했습니다` 500 에러 발생

AN 담당자 : @haeum808 

### 요청
```
2024-08-02 16:09:25.899 27994-28176
{
    "name":"cqwc",
    "date":"2024-08-27",
    "time":"16:09",
    "targetAddress":"서울 광진구 아차산로187",
    "targetLatitude":"37.542487",
    "targetLongitude":"127.06477",
    "nickname":"cqw2",
    "originAddress":"서울 마포구 굴레방로 1",
    "originLatitude":"37.554560",
    "originLongitude":"126.95683"
}
```
#### 응답
```
500 http://43.201.206.39/meetings (44ms)
{
    "type":"about:blank",
    "title":"Internal Server Error",
    "status":500,
    "detail":"모임 구독에 실패했습니다",
    "instance":"/meetings"
}
HTTP 500
```

### 서버 로그
```
2024-08-02T16:09:29.037+09:00 ERROR 1 --- [nio-8080-exec-7] c.o.notification.service.FcmSubscriber   : FirebaseApp with name [DEFAULT] doesn't exist.
2024-08-02T16:09:29.039+09:00 ERROR 1 --- [   scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task

java.lang.IllegalStateException: FirebaseApp with name [DEFAULT] doesn't exist.
	at com.google.firebase.FirebaseApp.getInstance(FirebaseApp.java:161) ~[firebase-admin-9.2.0.jar!/:na]
	at com.google.firebase.FirebaseApp.getInstance(FirebaseApp.java:132) ~[firebase-admin-9.2.0.jar!/:na]
	at com.google.firebase.messaging.FirebaseMessaging.getInstance(FirebaseMessaging.java:64) ~[firebase-admin-9.2.0.jar!/:na]
	at com.ody.notification.service.FcmPushSender.sendPushNotification(FcmPushSender.java:28) ~[!/:0.0.1-SNAPSHOT]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:354) ~[spring-aop-6.1.10.jar!/:6.1.10]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196) ~[spring-aop-6.1.10.jar!/:6.1.10]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-6.1.10.jar!/:6.1.10]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768) ~[spring-aop-6.1.10.jar!/:6.1.10]
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123) ~[spring-tx-6.1.10.jar!/:6.1.10]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:392) ~[spring-tx-6.1.10.jar!/:6.1.10]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) ~[spring-tx-6.1.10.jar!/:6.1.10]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.1.10.jar!/:6.1.10]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768) ~[spring-aop-6.1.10.jar!/:6.1.10]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:720) ~[spring-aop-6.1.10.jar!/:6.1.10]
	at com.ody.notification.service.FcmPushSender$$SpringCGLIB$$0.sendPushNotification(<generated>) ~[!/:0.0.1-SNAPSHOT]
	at com.ody.notification.service.NotificationService.lambda$scheduleNotification$0(NotificationService.java:74) ~[!/:0.0.1-SNAPSHOT]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-6.1.10.jar!/:6.1.10]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
```
* EC2 서버 로그 확인 명령어 : `docker logs -f ody-backend`

**Comment by hyeon0208** [comment]
@eun-byeol
기존에 private 서브 모듈 안에 있던 변경된 fcm 엑세스 키 파일명이 반영되지 않은 이전 브랜치를
develop 브랜치에 있는 FCM 연결 코드가 참조하고 있어서 발생하던 문제인 것 같아요
현재 "약속 참여자 상태 목록 조회 API 문서화" PR에서 해당 서브 모듈에도 변경된 파일 명이 적용되도록 다시 코드를 수정후 push 해서
머지 후에 다시 확인해봐야할 것 같아요 👍🏻

**Comment by eun-byeol** [comment]
서브모듈 수정 시,
`서브모듈 commit & push` 후에 `메인모듈 commit & push` **순서**에 유의해주세요!
순서가 바뀌면 서브모듈 수정사항이 메인모듈에 반영되지 않아요.

서브모듈 관련 상세 내용은 `ody 노션 > 기술공유 > 서브모듈 사용법` 참고하시면 좋아요:)

**Comment by hyeon0208** [comment]
@haeum808 @eun-byeol 
약속 참여자 상태 목록 조회 API merge되어 
develop 브랜치의 private 서브 모듈의 firebase accesskey 파일명이 올바르게 바뀐것으로보아 
해당 이슈 해결되었을 것 같아요 !
해음이 한 번 확인해주시고 이상없으면 이슈닫아도 될 것 같네용

**Comment by mzeong** [comment]
이후 동일한 문제가 있다고 전달받아 서브 모듈에 제대로 반영했습니다
217a4a34400cf236035c06fbcc3836e08224048a 커밋이 머지된 이후 문제가 해결되었음을 확인하여 이슈를 닫습니다!
